load("@rules_python//python:py_binary.bzl", "py_binary")

py_binary(
    name="check_sugarcube_macros",
    srcs=[
        "check_sugarcube_macros.py",
    ],
    visibility=["//visibility:public"],
)

filegroup(
    name="builtin_macros",
    srcs=[
        "sugarcube_macro_list.json",
    ],
    visibility=["//visibility:public"],
)

py_binary(
    name="extract_passage",
    srcs=[
        "extract_passage.py",
    ],
    visibility=["//visibility:public"],
)

py_binary(
    name="extract_story",
    srcs=[
        "extract_story.py",
    ],
    visibility=["//visibility:public"],
)

py_binary(
    name="scp_to_html",
    srcs=[
        "scp_to_html.py",
    ],
    visibility=["//visibility:public"],
)

py_binary(
    name="scp_to_tw",
    srcs=[
        "scp_to_tw.py",
    ],
    visibility=["//visibility:public"],
)

py_binary(
    name="make_story",
    srcs=[
        "make_story.py",
    ],
    visibility=["//visibility:public"],
)
