load("@sugarcube_bazel//:defs.bzl", "sugarcube_story")

package(default_visibility=["//:__subpackages__"])

filegroup(
    name="extras",
    srcs=["user_script.js", "user_stylesheet.css"],
)

filegroup(
    name="user_macros",
    srcs=["user_macros.json"],
)

sugarcube_story(
    name="the_mall",
    title="The Mall",
    ifid="FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF",
    extra_html=[":extras"],
    user_macros=[":user_macros"],
    deps=[
        "//passages:start",
    ],
)
